-- Demo seed for 5 fictional Ceylon Wellness travel journeys.
-- Safe, additive, and idempotent: rerunning this file does not overwrite real traveller records.
-- Each insert is gated by journey_ref so the same demo records are not duplicated.

insert into public.leads (
  name,
  country,
  email,
  whatsapp,
  travel_dates,
  duration,
  travellers,
  wellness_interests,
  journey_style,
  accommodation,
  transport,
  budget_range,
  requirements,
  consent,
  consent_at,
  privacy_version,
  source,
  status,
  preferred_language,
  delivery_preference,
  journey_ref,
  itinerary,
  arrival_airport,
  flight_number,
  landing_time,
  airport_pickup,
  currency,
  total_price,
  advance_deposit_type,
  advance_deposit_value,
  advance_amount,
  remaining_balance,
  advance_due_date,
  balance_due_date,
  quotation_valid_until,
  booking_status,
  accommodation_booking_status,
  transport_booking_status,
  wellness_booking_status,
  accommodation_booking_details,
  transport_booking_details,
  wellness_booking_details,
  price_includes,
  price_excludes,
  traveller_payment_instructions,
  traveller_cancellation_terms,
  admin_notes,
  internal_commercial_notes,
  created_at,
  updated_at
)
select
  'Emma Carter',
  'United Kingdom',
  'emma.carter@example.com',
  '+44 7700 900001',
  '15 Nov 2026 – 21 Nov 2026',
  '7 days / 6 nights',
  2,
  ARRAY['Ayurveda','Nature','Tea','Wellness','Relaxation']::text[],
  'Wellness · Ayurveda · Nature · Slow Travel',
  'Comfort / Boutique 4★',
  'Private vehicle with driver',
  'Mid-range / Premium',
  'Relaxed pace, Ayurveda experience, nature, tea country and beach time.',
  true,
  now(),
  'DEMO-ONLY',
  'demo-seed',
  'NEW',
  'EN',
  'Email + WhatsApp',
  'DEMO-CW-001',
  jsonb_build_array(
    jsonb_build_object('day',1,'place','Negombo','focus','Arrive · Rest · Reset','activity','Airport pickup, hotel check-in, gentle introduction and relaxed evening.','stay','Boutique hotel in Negombo','notes','Keep the first day light after the flight.'),
    jsonb_build_object('day',2,'place','Kandy','focus','Nature · Culture · Mindfulness','activity','Scenic journey to Kandy, cultural highlights and relaxed evening.','stay','Boutique hotel in Kandy','notes',''),
    jsonb_build_object('day',3,'place','Kandy','focus','Ayurveda · Recovery','activity','Wellness consultation, Ayurveda treatment and free relaxation time.','stay','Boutique hotel in Kandy','notes',''),
    jsonb_build_object('day',4,'place','Nuwara Eliya / Tea Country','focus','Nature · Tea · Fresh Air','activity','Scenic hill-country journey, tea experience and gentle nature walk.','stay','Hill-country hotel','notes',''),
    jsonb_build_object('day',5,'place','Bentota','focus','Ocean · Rest','activity','Transfer to the south-west coast, beach relaxation and optional wellness treatment.','stay','Beach hotel','notes',''),
    jsonb_build_object('day',6,'place','Bentota','focus','Wellness · Free Time','activity','Slow morning, wellness session and flexible beach time.','stay','Beach hotel','notes',''),
    jsonb_build_object('day',7,'place','Colombo / Airport','focus','Departure','activity','Easy departure day and airport transfer according to confirmed flight.','stay','Departure day','notes','')
  ),
  'CMB · Bandaranaike International Airport',
  'Demo Flight UL-001',
  '09:30',
  'Included',
  'EUR',
  2450,
  'percentage',
  30,
  735,
  1715,
  '2026-10-25',
  '2026-11-07',
  '2026-11-10',
  'DRAFT',
  'Pending',
  'Pending',
  'Pending',
  'Demo accommodation placeholder record only.',
  'Demo transport placeholder record only.',
  'Demo wellness placeholder record only.',
  'Airport transfers, private transport, accommodation, selected breakfast, planned wellness experiences and itinerary coordination.',
  'International flights, visa costs, personal expenses, optional activities and services not listed as included.',
  '30% advance after final quotation confirmation. Remaining balance according to confirmed payment schedule.',
  'Cancellation conditions depend on confirmed hotels, wellness providers and suppliers. Final terms must be confirmed before payment.',
  'DEMO RECORD — safe for testing. Not a real traveller.',
  'Demo only — no real supplier booking.',
  now(),
  now()
where not exists (select 1 from public.leads where journey_ref = 'DEMO-CW-001');

insert into public.leads (
  name,
  country,
  email,
  whatsapp,
  travel_dates,
  duration,
  travellers,
  wellness_interests,
  journey_style,
  accommodation,
  transport,
  budget_range,
  requirements,
  consent,
  consent_at,
  privacy_version,
  source,
  status,
  preferred_language,
  delivery_preference,
  journey_ref,
  itinerary,
  arrival_airport,
  flight_number,
  landing_time,
  airport_pickup,
  currency,
  total_price,
  advance_deposit_type,
  advance_deposit_value,
  advance_amount,
  remaining_balance,
  advance_due_date,
  balance_due_date,
  quotation_valid_until,
  booking_status,
  accommodation_booking_status,
  transport_booking_status,
  wellness_booking_status,
  accommodation_booking_details,
  transport_booking_details,
  wellness_booking_details,
  price_includes,
  price_excludes,
  traveller_payment_instructions,
  traveller_cancellation_terms,
  admin_notes,
  internal_commercial_notes,
  created_at,
  updated_at
)
select
  'Anna Kowalska',
  'Poland',
  'anna.kowalska@example.com',
  '+48 600 000 002',
  '5 Dec 2026 – 14 Dec 2026',
  '10 days / 9 nights',
  1,
  ARRAY['Ayurveda','Meditation','Wellness','Reiki','Nature']::text[],
  'Ayurveda · Deep Relaxation · Premium Wellness',
  'Premium Wellness / 4–5★',
  'Private transfer',
  'Premium',
  'Wellness-focused trip with a calm schedule and minimal daily travelling.',
  true,
  now(),
  'DEMO-ONLY',
  'demo-seed',
  'QUALIFYING',
  'PL',
  'WhatsApp only',
  'DEMO-CW-002',
  jsonb_build_array(
    jsonb_build_object('day',1,'place','Negombo','focus','Arrival and rest','activity','Private airport pickup, check-in and rest.','stay','Negombo boutique stay','notes','Easy arrival after flight.'),
    jsonb_build_object('day',2,'place','Wellness Resort','focus','Initial consultation','activity','Initial wellness consultation and personalised programme introduction.','stay','Wellness resort','notes',''),
    jsonb_build_object('day',3,'place','Wellness Resort','focus','Ayurveda treatment','activity','Ayurveda treatment, restorative meals and relaxation.','stay','Wellness resort','notes',''),
    jsonb_build_object('day',4,'place','Wellness Resort','focus','Wellness programme','activity','Ayurveda programme, yoga and quiet personal time.','stay','Wellness resort','notes',''),
    jsonb_build_object('day',5,'place','Wellness Resort','focus','Treatment programme','activity','Treatment programme and gentle nature experience.','stay','Wellness resort','notes',''),
    jsonb_build_object('day',6,'place','Wellness Resort','focus','Ayurveda and meditation','activity','Ayurveda, meditation and relaxation.','stay','Wellness resort','notes',''),
    jsonb_build_object('day',7,'place','Wellness Resort','focus','Treatment programme','activity','Treatment programme and optional cultural activity.','stay','Wellness resort','notes',''),
    jsonb_build_object('day',8,'place','Wellness Resort','focus','Recovery time','activity','Wellness programme and personal recovery time.','stay','Wellness resort','notes',''),
    jsonb_build_object('day',9,'place','Negombo / Colombo Area','focus','Final overnight','activity','Relaxed final overnight and journey review.','stay','Negombo / Colombo area','notes',''),
    jsonb_build_object('day',10,'place','Airport','focus','Departure','activity','Private airport transfer and departure.','stay','Departure day','notes','')
  ),
  'CMB',
  'Demo Flight LO-002',
  '07:45',
  'Included',
  'PLN',
  12500,
  'percentage',
  25,
  3125,
  9375,
  '2026-10-28',
  '2026-12-12',
  '2026-12-15',
  'DRAFT',
  'Pending',
  'Pending',
  'Pending',
  'Demo accommodation placeholder record only.',
  'Demo transport placeholder record only.',
  'Demo wellness placeholder record only.',
  'Accommodation, planned wellness programme, selected meals according to confirmed programme, private airport transfers and journey coordination.',
  'Flights, visa, insurance, personal shopping and optional services.',
  '25% advance after final confirmation. Remaining balance according to the final payment plan.',
  'Final standard cancellation terms are provided only after confirmation of resort and wellness programme availability.',
  'DEMO RECORD — safe for testing. Not a real traveller.',
  'Demo only — no real supplier booking.',
  now(),
  now()
where not exists (select 1 from public.leads where journey_ref = 'DEMO-CW-002');

insert into public.leads (
  name,
  country,
  email,
  whatsapp,
  travel_dates,
  duration,
  travellers,
  wellness_interests,
  journey_style,
  accommodation,
  transport,
  budget_range,
  requirements,
  consent,
  consent_at,
  privacy_version,
  source,
  status,
  preferred_language,
  delivery_preference,
  journey_ref,
  itinerary,
  arrival_airport,
  flight_number,
  landing_time,
  airport_pickup,
  currency,
  total_price,
  advance_deposit_type,
  advance_deposit_value,
  advance_amount,
  remaining_balance,
  advance_due_date,
  balance_due_date,
  quotation_valid_until,
  booking_status,
  accommodation_booking_status,
  transport_booking_status,
  wellness_booking_status,
  accommodation_booking_details,
  transport_booking_details,
  wellness_booking_details,
  price_includes,
  price_excludes,
  traveller_payment_instructions,
  traveller_cancellation_terms,
  admin_notes,
  internal_commercial_notes,
  created_at,
  updated_at
)
select
  'Daniel Weber',
  'Germany',
  'daniel.weber@example.com',
  '+49 151 00000003',
  '10 Jan 2027 – 17 Jan 2027',
  '8 days / 7 nights',
  2,
  ARRAY['Culture','Nature','Wellness','Travel']::text[],
  'Couple · Wellness · Culture · Nature',
  'Boutique 4★',
  'Private car + driver',
  'Comfort / Premium',
  'A slow-burn couple route with cultural highlights, relaxed wellness time and gentle movement.',
  true,
  now(),
  'DEMO-ONLY',
  'demo-seed',
  'NEW',
  'DE',
  'Email + WhatsApp',
  'DEMO-CW-003',
  jsonb_build_array(
    jsonb_build_object('day',1,'place','Negombo','focus','Arrival and recovery','activity','Arrival and recovery.','stay','Negombo stay','notes','Easy first day after flight.'),
    jsonb_build_object('day',2,'place','Sigiriya Area','focus','Scenic transfer and cultural introduction','activity','Scenic transfer and relaxed cultural introduction.','stay','Sigiriya stay','notes',''),
    jsonb_build_object('day',3,'place','Sigiriya','focus','Culture, nature and wellness','activity','Culture, nature and flexible wellness time.','stay','Sigiriya stay','notes',''),
    jsonb_build_object('day',4,'place','Kandy','focus','Transfer and culture','activity','Transfer to Kandy, cultural discovery and relaxed evening.','stay','Kandy boutique stay','notes',''),
    jsonb_build_object('day',5,'place','Kandy','focus','Wellness experience','activity','Wellness experience, botanical/nature time and free evening.','stay','Kandy boutique stay','notes',''),
    jsonb_build_object('day',6,'place','Tea Country','focus','Scenic hill country','activity','Scenic journey through the hill country and tea experience.','stay','Tea-country stay','notes',''),
    jsonb_build_object('day',7,'place','Colombo / Negombo','focus','Return and final evening','activity','Return toward the airport region, relaxed final evening.','stay','Return-area hotel','notes',''),
    jsonb_build_object('day',8,'place','Airport','focus','Departure','activity','Departure transfer.','stay','Departure day','notes','')
  ),
  'CMB',
  'Demo Flight DE-003',
  '08:15',
  'Included',
  'EUR',
  2950,
  'percentage',
  30,
  885,
  2065,
  '2026-10-21',
  '2027-01-13',
  '2027-01-20',
  'DRAFT',
  'Pending',
  'Pending',
  'Pending',
  'Demo accommodation placeholder record only.',
  'Demo transport placeholder record only.',
  'Demo wellness placeholder record only.',
  'Accommodation, private driver, wellness time and itinerary coordination.',
  'International flights, visa, personal shopping and optional experiences.',
  '30% advance after quotation confirmation. Balance according to the final payment schedule.',
  'Cancellation terms are finalised after hotels and providers are confirmed.',
  'DEMO RECORD — safe for testing. Not a real traveller.',
  'Demo only — no real supplier booking.',
  now(),
  now()
where not exists (select 1 from public.leads where journey_ref = 'DEMO-CW-003');

insert into public.leads (
  name,
  country,
  email,
  whatsapp,
  travel_dates,
  duration,
  travellers,
  wellness_interests,
  journey_style,
  accommodation,
  transport,
  budget_range,
  requirements,
  consent,
  consent_at,
  privacy_version,
  source,
  status,
  preferred_language,
  delivery_preference,
  journey_ref,
  itinerary,
  arrival_airport,
  flight_number,
  landing_time,
  airport_pickup,
  currency,
  total_price,
  advance_deposit_type,
  advance_deposit_value,
  advance_amount,
  remaining_balance,
  advance_due_date,
  balance_due_date,
  quotation_valid_until,
  booking_status,
  accommodation_booking_status,
  transport_booking_status,
  wellness_booking_status,
  accommodation_booking_details,
  transport_booking_details,
  wellness_booking_details,
  price_includes,
  price_excludes,
  traveller_payment_instructions,
  traveller_cancellation_terms,
  admin_notes,
  internal_commercial_notes,
  created_at,
  updated_at
)
select
  'Sofia Ivanova',
  'Bulgaria',
  'sofia.ivanova@example.com',
  '+359 88 000 0004',
  '3 Feb 2027 – 8 Feb 2027',
  '6 days / 5 nights',
  1,
  ARRAY['Nature','Wellness','Local Discovery','Budget Travel']::text[],
  'Budget Wellness · Nature · Local Discovery',
  'Good-value guesthouses / 3★',
  'Optimised private/shared transport according to final plan',
  'Budget Friendly',
  'A straightforward wellness route with nature, local discovery and a gentle travel pace.',
  true,
  now(),
  'DEMO-ONLY',
  'demo-seed',
  'NEW',
  'RU',
  'Email + WhatsApp',
  'DEMO-CW-004',
  jsonb_build_array(
    jsonb_build_object('day',1,'place','Negombo','focus','Arrival, rest and orientation','activity','Arrival, rest and orientation.','stay','Negombo guesthouse','notes','Easy first evening after landing.'),
    jsonb_build_object('day',2,'place','Kandy','focus','Transfer and local discovery','activity','Transfer, local discovery and relaxed evening.','stay','Guesthouse in Kandy','notes',''),
    jsonb_build_object('day',3,'place','Kandy','focus','Affordable wellness experience','activity','Affordable wellness experience and cultural exploration.','stay','Guesthouse in Kandy','notes',''),
    jsonb_build_object('day',4,'place','Hill Country','focus','Nature, viewpoints and tea-country experience','activity','Nature, viewpoints and tea-country experience.','stay','Hill-country guesthouse','notes',''),
    jsonb_build_object('day',5,'place','Colombo / Negombo','focus','Return journey and relaxed final day','activity','Return journey and flexible final day.','stay','Negombo stay','notes',''),
    jsonb_build_object('day',6,'place','Airport','focus','Departure','activity','Departure transfer.','stay','Departure day','notes','')
  ),
  'CMB',
  'Demo Flight RU-004',
  '08:10',
  'Included',
  'EUR',
  980,
  'percentage',
  20,
  196,
  784,
  '2026-11-13',
  '2027-02-02',
  '2027-02-11',
  'DRAFT',
  'Pending',
  'Pending',
  'Pending',
  'Demo accommodation placeholder record only.',
  'Demo transport placeholder record only.',
  'Demo wellness placeholder record only.',
  'Guesthouse accommodation, value transport and planned wellness experiences.',
  'Flights, visa, shopping and optional activities.',
  '20% advance after final quotation confirmation. Remaining balance according to the final schedule.',
  'Budget travel cancellation rules depend on final selected guesthouses and transport providers.',
  'DEMO RECORD — safe for testing. Not a real traveller.',
  'Demo only — no real supplier booking.',
  now(),
  now()
where not exists (select 1 from public.leads where journey_ref = 'DEMO-CW-004');

insert into public.leads (
  name,
  country,
  email,
  whatsapp,
  travel_dates,
  duration,
  travellers,
  wellness_interests,
  journey_style,
  accommodation,
  transport,
  budget_range,
  requirements,
  consent,
  consent_at,
  privacy_version,
  source,
  status,
  preferred_language,
  delivery_preference,
  journey_ref,
  itinerary,
  arrival_airport,
  flight_number,
  landing_time,
  airport_pickup,
  currency,
  total_price,
  advance_deposit_type,
  advance_deposit_value,
  advance_amount,
  remaining_balance,
  advance_due_date,
  balance_due_date,
  quotation_valid_until,
  booking_status,
  accommodation_booking_status,
  transport_booking_status,
  wellness_booking_status,
  accommodation_booking_details,
  transport_booking_details,
  wellness_booking_details,
  price_includes,
  price_excludes,
  traveller_payment_instructions,
  traveller_cancellation_terms,
  admin_notes,
  internal_commercial_notes,
  created_at,
  updated_at
)
select
  'Olivia Martin',
  'France',
  'olivia.martin@example.com',
  '+33 6 00 00 00 05',
  '15 Mar 2027 – 23 Mar 2027',
  '9 days / 8 nights',
  2,
  ARRAY['Luxury','Ayurveda','Wildlife','Beach','Wellness']::text[],
  'Luxury Wellness · Ayurveda · Wildlife · Beach',
  'Premium Boutique / 5★',
  'Private premium vehicle with driver',
  'Luxury',
  'A premium beach-and-wellness route with private transfers, quiet recovery space and gentle exploration.',
  true,
  now(),
  'DEMO-ONLY',
  'demo-seed',
  'QUALIFYING',
  'FR',
  'WhatsApp only',
  'DEMO-CW-005',
  jsonb_build_array(
    jsonb_build_object('day',1,'place','Negombo','focus','VIP airport pickup and recovery','activity','VIP airport pickup and recovery.','stay','Negombo premium stay','notes','Easy arrival and minimal schedule.'),
    jsonb_build_object('day',2,'place','Kandy','focus','Private scenic transfer and culture','activity','Private scenic transfer, cultural experience and premium stay.','stay','Premium Kandy stay','notes',''),
    jsonb_build_object('day',3,'place','Kandy','focus','Private wellness experience','activity','Private wellness experience and relaxed exploration.','stay','Premium Kandy stay','notes',''),
    jsonb_build_object('day',4,'place','Hill Country','focus','Tea-country and premium nature stay','activity','Tea-country journey and premium nature stay.','stay','Premium hill-country lodge','notes',''),
    jsonb_build_object('day',5,'place','Yala / Southern Region','focus','Scenic transfer toward the south','activity','Scenic transfer toward the south and relaxed evening.','stay','Southern stay','notes',''),
    jsonb_build_object('day',6,'place','Southern Region','focus','Wildlife and recovery','activity','Wildlife experience followed by recovery time.','stay','Southern stay','notes',''),
    jsonb_build_object('day',7,'place','South Coast','focus','Beach wellness','activity','Beach wellness and private relaxation.','stay','Coastal luxury stay','notes',''),
    jsonb_build_object('day',8,'place','South Coast','focus','Flexible premium wellness','activity','Flexible premium wellness and beach day.','stay','Coastal luxury stay','notes',''),
    jsonb_build_object('day',9,'place','Colombo / Airport','focus','Private departure transfer','activity','Private departure transfer.','stay','Departure day','notes','')
  ),
  'CMB',
  'Demo Flight FR-005',
  '09:00',
  'Private VIP transfer',
  'EUR',
  4850,
  'percentage',
  30,
  1455,
  3395,
  '2026-11-30',
  '2027-03-19',
  '2027-03-27',
  'DRAFT',
  'Pending',
  'Pending',
  'Pending',
  'Demo accommodation placeholder record only.',
  'Demo transport placeholder record only.',
  'Demo wellness placeholder record only.',
  'Private VIP airport support, premium travel, planned wellness activities, accommodation and itinerary coordination.',
  'Flights, visa, personal shopping, optional add-ons and any services not explicitly listed as included.',
  '30% advance after final quotation confirmation. Remaining balance due according to the final payment schedule.',
  'Cancellation conditions depend on confirmed luxury accommodation and supplier terms before payment.',
  'DEMO RECORD — safe for testing. Not a real traveller.',
  'Demo only — no real supplier booking.',
  now(),
  now()
where not exists (select 1 from public.leads where journey_ref = 'DEMO-CW-005');
