import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Heart, Leaf, Compass, HandHeart, Sparkles, Sun, Flower2, Palette, Utensils, Waves } from 'lucide-react';
import './AboutPage.css';

type Props = { lang?: string };

const translated: Record<string,string[]> = {
 "PL": [
  "CEYLON WELLNESS · NASZA HISTORIA",
  "Wellness dzięki wiedzy, relacjom i doświadczeniom.",
  "Dzielimy się wiedzą, odkrywamy, czym jest dobrostan, i ułatwiamy dostęp do wartościowych doświadczeń wellness na Sri Lance.",
  "Poznaj naszą misję",
  "Odkryj wellness",
  "DLACZEGO ISTNIEJEMY",
  "Wellness nie jest luksusem. To podróż, którą możemy dzielić.",
  "Ceylon Wellness to platforma wymiany wiedzy i doświadczeń dla osób zainteresowanych dobrostanem fizycznym, psychicznym i duchowym.",
  "Stworzyliśmy to miejsce, aby dzielić się wiedzą i doświadczeniami, przedstawiać tradycje wellness i łączyć osoby szukające bardziej świadomego życia.",
  "Nie jesteśmy tu tylko po to, by sprzedawać wycieczki. Podróże to jeden ze sposobów doświadczania wellness, a nie cel istnienia naszej społeczności.",
  "Wierzymy, że wartościowe doświadczenia wellness powinny być dostępne dla różnych budżetów. Pomagamy znaleźć dobre rozwiązania w uczciwych cenach.",
  "DWA SPOSOBY NA POŁĄCZENIE",
  "Ucz się, gdziekolwiek jesteś. Doświadczaj, gdy będziesz gotowy.",
  "01 · WIEDZA",
  "Ucz się i dziel",
  "Poznaj medytację, uważność, jogę, Reiki, duchowość, kontakt z naturą i świadome życie — bez narzucania przekonań.",
  "Przejdź do przewodnika wellness",
  "02 · DOŚWIADCZENIA",
  "Odkrywaj i doświadczaj",
  "Jeśli chcesz pójść dalej, pomożemy Ci poznać odpowiednie miejsca i aktywności na Sri Lance. Nasz zespół uwzględnia zainteresowania, czas i budżet.",
  "Powiedz nam, co jest dla Ciebie ważne",
  "ODKRYJ WŁASNĄ DROGĘ",
  "Sześć ścieżek do dobrostanu.",
  "Różne tradycje oferują różne sposoby odkrywania wellness. Zacznij od tego, co Cię interesuje.",
  "Uważność, duchowość i wewnętrzny spokój",
  "Poznaj medytację, uważność, tradycje duchowe i spokojną refleksję.",
  "Ruch i świadomość ciała",
  "Poznaj jogę, świadomy ruch i tradycyjne praktyki Sri Lanki, w tym Angamporę.",
  "Energia i tradycje holistyczne",
  "Odkryj Reiki, medytację czakr, relaksację dźwiękiem i inne tradycje z szacunkiem dla różnych przekonań.",
  "Natura i ekologiczny wellness",
  "Odkryj lasy, góry, plantacje herbaty i wybrzeża Sri Lanki w spokojnym rytmie.",
  "Świadome odżywianie i życie",
  "Poznaj lokalne składniki, kuchnię Sri Lanki i świadome nawyki.",
  "Kreatywność i ekspresja",
  "Poznaj pisanie, malowanie, muzykę i ruch jako przestrzeń do refleksji.",
  "CO JEST DLA NAS WAŻNE",
  "Ludzie przed pakietami. Sens przed ceną.",
  "Tworzymy otwartą przestrzeń do nauki, rozmowy i osobistych doświadczeń.",
  "Otwartość dla wszystkich",
  "Zapraszamy osoby o różnych przekonaniach, doświadczeniach i pochodzeniu.",
  "Wiedza dostępna dla każdego",
  "Dzielimy się wiedzą i uczymy od innych.",
  "Uczciwa wartość",
  "Stawiamy na jakość i przejrzyste, rozsądne koszty.",
  "Szacunek dla ludzi i miejsc",
  "Szanujemy tradycje Sri Lanki, społeczności i przyrodę.",
  "SRI LANKA, OSOBISTE DOŚWIADCZENIE",
  "Nie standardowa wycieczka. Twoje doświadczenie wellness.",
  "Jedni chcą medytować, inni spędzać czas w naturze, poznawać kulturę, jogę lub Reiki. Najpierw słuchamy, potem pomagamy zaplanować realną podróż.",
  "Przez Ask Ceylon możesz opisać swoje preferencje. Nasz zespół przygotuje propozycję i wycenę. Żadna rezerwacja nie jest potwierdzona przed ustaleniami i płatnością.",
  "Zaprojektuj podróż — zapytanie bezpłatne",
  "Wartość podróży wellness mierzymy tym, czego się uczysz, co czujesz i odkrywasz — nie kwotą wydatków.",
  "PODEJŚCIE CEYLON WELLNESS",
  "NASZE ZAPROSZENIE",
  "Zacznij od ciekawości. Znajdź własną drogę.",
  "Niezależnie od tego, czy chcesz się uczyć, dzielić wiedzą czy poznawać Sri Lankę — zapraszamy.",
  "Odkryj wellness",
  "Poznaj osobistą podróż",
  "Nasze treści i doświadczenia służą edukacji, relaksacji i ogólnemu dobrostanowi. Reiki i inne praktyki energetyczne nie są przedstawiane jako naukowo potwierdzone leczenie. Nie zastępują opieki medycznej ani psychologicznej."
 ],
 "RU": [
  "CEYLON WELLNESS · НАША ИСТОРИЯ",
  "Благополучие через знания, общение и опыт.",
  "Мы делимся знаниями, исследуем смысл благополучия и делаем ценный опыт оздоровления на Шри-Ланке доступнее.",
  "Узнать о нашей миссии",
  "Открыть wellness",
  "ЗАЧЕМ МЫ СУЩЕСТВУЕМ",
  "Благополучие — не роскошь. Это путь, которым можно делиться.",
  "Ceylon Wellness — платформа обмена знаниями и опытом для тех, кому важно физическое, психическое и духовное благополучие.",
  "Мы создали это пространство, чтобы делиться знаниями, знакомить с традициями и объединять людей, стремящихся к осознанной жизни.",
  "Мы не просто продаём туры. Путешествия — лишь один из способов познакомиться с wellness, но не цель нашего сообщества.",
  "Мы считаем, что значимый опыт должен быть доступен при разном бюджете. Мы помогаем находить качественные варианты по справедливой цене.",
  "ДВА СПОСОБА ОБЩЕНИЯ",
  "Учитесь где угодно. Пробуйте, когда будете готовы.",
  "01 · ЗНАНИЯ",
  "Учиться и делиться",
  "Исследуйте медитацию, осознанность, йогу, Рейки, духовные традиции, природу и осознанную жизнь без навязывания убеждений.",
  "Открыть гид по wellness",
  "02 · ОПЫТ",
  "Исследовать и пробовать",
  "Если хотите большего, мы поможем подобрать занятия и места на Шри-Ланке с учётом ваших интересов, времени и бюджета.",
  "Расскажите, что вам важно",
  "НАЙДИТЕ СВОЙ ПУТЬ",
  "Шесть путей к благополучию.",
  "Разные традиции открывают разные возможности. Начните с того, что вам интересно.",
  "Осознанность, духовность и внутренний покой",
  "Откройте медитацию, осознанность, духовные традиции и спокойное размышление.",
  "Движение и осознание тела",
  "Узнайте о йоге, осознанном движении и традиционных практиках Шри-Ланки, включая ангампору.",
  "Энергетические и холистические традиции",
  "Познакомьтесь с Рейки, медитацией чакр и звуковой релаксацией с уважением к разным взглядам.",
  "Природа и эко-wellness",
  "Откройте леса, горы, чайные плантации и побережья Шри-Ланки в спокойном ритме.",
  "Осознанное питание и образ жизни",
  "Исследуйте местные продукты, кухню Шри-Ланки и полезные повседневные привычки.",
  "Творчество и самовыражение",
  "Попробуйте письмо, рисование, музыку и движение для размышления и самовыражения.",
  "НАШИ ЦЕННОСТИ",
  "Люди важнее пакетов. Смысл важнее ценников.",
  "Мы создаём открытое пространство для обучения, общения и личного опыта.",
  "Открыто для всех",
  "Мы рады людям с разным опытом, происхождением и убеждениями.",
  "Свободный обмен знаниями",
  "Мы делимся тем, что знаем, и учимся у других.",
  "Честная ценность",
  "Качественный опыт по разумной и прозрачной цене.",
  "Уважение к людям и месту",
  "Мы ценим традиции Шри-Ланки, местные сообщества и природу.",
  "ШРИ-ЛАНКА, ЛИЧНЫЙ ОПЫТ",
  "Не стандартный тур. Ваш собственный wellness-опыт.",
  "Кому-то близка медитация, другим — природа, культура, йога или Рейки. Сначала мы слушаем, затем помогаем спланировать реальное путешествие.",
  "В Ask Ceylon расскажите о пожеланиях. Наша команда подготовит план и стоимость. Бронирование не считается подтверждённым до согласования и оплаты.",
  "Создать маршрут — запрос бесплатный",
  "Ценность wellness-путешествия — в том, что вы узнаёте, чувствуете и открываете, а не в сумме расходов.",
  "ПОДХОД CEYLON WELLNESS",
  "НАШЕ ПРИГЛАШЕНИЕ",
  "Начните с любопытства. Найдите свой путь.",
  "Хотите учиться, делиться или по-новому открыть Шри-Ланку? Добро пожаловать.",
  "Открыть wellness",
  "Исследовать личный маршрут",
  "Наши материалы предназначены для обучения, отдыха и общего благополучия. Рейки и другие энергетические практики не являются научно доказанным лечением и не заменяют медицинскую или психологическую помощь."
 ],
 "DE": [
  "CEYLON WELLNESS · UNSERE GESCHICHTE",
  "Wohlbefinden durch Wissen, Verbindung und Erfahrung.",
  "Wir teilen Wissen, erkunden die Bedeutung von Wohlbefinden und machen wertvolle Wellness-Erfahrungen in Sri Lanka zugänglicher.",
  "Unsere Mission entdecken",
  "Wellness entdecken",
  "WARUM ES UNS GIBT",
  "Wellness ist kein Luxus. Es ist ein Weg, den wir teilen können.",
  "Ceylon Wellness ist eine Plattform für Wissens- und Erfahrungsaustausch rund um körperliches, mentales und spirituelles Wohlbefinden.",
  "Wir teilen Wissen und persönliche Erfahrungen, stellen Traditionen vor und verbinden Menschen, die bewusster leben möchten.",
  "Wir verkaufen nicht einfach Reisepakete. Reisen sind eine Möglichkeit, Wellness zu erleben – nicht der Zweck unserer Gemeinschaft.",
  "Bedeutsame Erfahrungen sollten für unterschiedliche Budgets möglich sein. Wir helfen, Qualität zu fairen Preisen zu finden.",
  "ZWEI WEGE ZUR VERBINDUNG",
  "Lernen, wo immer du bist. Erleben, wenn du bereit bist.",
  "01 · WISSEN",
  "Lernen und teilen",
  "Entdecke Meditation, Achtsamkeit, Yoga, Reiki, Spiritualität, Natur und bewusstes Leben – ohne vorgeschriebene Glaubensrichtung.",
  "Zum Wellness-Ratgeber",
  "02 · ERFAHRUNG",
  "Entdecken und erleben",
  "Wir helfen, passende Aktivitäten und Orte in Sri Lanka zu finden – abgestimmt auf Interessen, Zeit und Budget.",
  "Sag uns, was dir wichtig ist",
  "ENTDECKE DEINEN WEG",
  "Sechs Wege zum Wohlbefinden.",
  "Unterschiedliche Traditionen eröffnen unterschiedliche Wege. Beginne mit dem, was dich interessiert.",
  "Achtsamkeit, Spiritualität und innerer Frieden",
  "Entdecke Meditation, Achtsamkeit, spirituelle Traditionen und stille Reflexion.",
  "Bewegung und Körperbewusstsein",
  "Lerne Yoga, achtsame Bewegung und Traditionen Sri Lankas wie Angampora kennen.",
  "Energie- und ganzheitliche Traditionen",
  "Erkunde Reiki, Chakra-Meditation und Klangentspannung mit Respekt vor verschiedenen Überzeugungen.",
  "Natur und Öko-Wellness",
  "Erlebe Wälder, Berge, Teeplantagen und Küsten Sri Lankas in einem ruhigeren Tempo.",
  "Achtsames Essen und Leben",
  "Entdecke regionale Zutaten, die Küche Sri Lankas und achtsame Gewohnheiten.",
  "Kreativität und Selbstausdruck",
  "Entdecke Schreiben, Malen, Musik und Bewegung als Raum für Reflexion.",
  "WAS UNS WICHTIG IST",
  "Menschen vor Paketen. Sinn vor Preisschildern.",
  "Wir möchten einen offenen Raum für Lernen, Gespräche und persönliche Erfahrungen schaffen.",
  "Offen für alle",
  "Menschen unterschiedlicher Herkunft, Überzeugungen und Erfahrung sind willkommen.",
  "Wissen frei teilen",
  "Wir teilen unser Wissen und lernen von anderen.",
  "Fairer Wert",
  "Qualität zu angemessenen, transparenten Kosten.",
  "Respekt für Menschen und Orte",
  "Wir schätzen Sri Lankas Traditionen, Gemeinschaften und Natur.",
  "SRI LANKA PERSÖNLICH ERLEBEN",
  "Keine Standardtour. Dein eigenes Wellness-Erlebnis.",
  "Manche suchen Meditation, andere Natur, Kultur, Yoga oder Reiki. Wir hören zuerst zu und planen dann gemeinsam eine realistische Reise.",
  "Teile deine Wünsche über Ask Ceylon. Unser Team erstellt einen individuellen Vorschlag mit Preis. Eine Buchung ist erst nach Vereinbarung und Zahlung bestätigt.",
  "Reise gestalten – Anfrage kostenlos",
  "Der Wert einer Wellness-Reise liegt darin, was du lernst, fühlst und entdeckst – nicht darin, wie viel du ausgibst.",
  "DER CEYLON-WELLNESS-ANSATZ",
  "UNSERE EINLADUNG",
  "Beginne mit Neugier. Finde deinen Weg.",
  "Ob du lernen, teilen oder Sri Lanka bewusst erleben möchtest – du bist willkommen.",
  "Wellness entdecken",
  "Persönliche Reise erkunden",
  "Unsere Inhalte dienen Bildung, Entspannung und allgemeinem Wohlbefinden. Reiki und andere Energiepraktiken gelten nicht als wissenschaftlich belegte medizinische Behandlung und ersetzen keine medizinische oder psychologische Betreuung."
 ],
 "FR": [
  "CEYLON WELLNESS · NOTRE HISTOIRE",
  "Le bien-être par la connaissance, les liens et l’expérience.",
  "Nous partageons nos connaissances, explorons le sens du bien-être et rendons les expériences de bien-être au Sri Lanka plus accessibles.",
  "Découvrir notre mission",
  "Explorer le bien-être",
  "POURQUOI NOUS EXISTONS",
  "Le bien-être n’est pas un luxe. C’est un chemin à partager.",
  "Ceylon Wellness est une plateforme de partage de connaissances et d’expériences autour du bien-être physique, mental et spirituel.",
  "Nous partageons nos expériences, présentons différentes traditions et réunissons des personnes en quête d’une vie plus consciente.",
  "Nous ne sommes pas là simplement pour vendre des voyages. Voyager est une façon de vivre le bien-être, pas la raison d’être de notre communauté.",
  "Nous pensons que les expériences enrichissantes doivent être accessibles à différents budgets, avec une qualité et des prix justes.",
  "DEUX FAÇONS DE SE RENCONTRER",
  "Apprenez où que vous soyez. Vivez l’expérience quand vous serez prêt.",
  "01 · CONNAISSANCE",
  "Apprendre et partager",
  "Découvrez la méditation, la pleine conscience, le yoga, le Reiki, la spiritualité, la nature et une vie attentive, sans croyance imposée.",
  "Explorer notre guide",
  "02 · EXPÉRIENCE",
  "Explorer et vivre",
  "Nous vous aidons à découvrir des activités et des lieux adaptés au Sri Lanka, selon vos envies, votre temps et votre budget.",
  "Dites-nous ce qui compte pour vous",
  "TROUVEZ VOTRE VOIE",
  "Six chemins vers le bien-être.",
  "Différentes traditions proposent différentes approches. Commencez par ce qui vous intéresse.",
  "Pleine conscience, spiritualité et paix intérieure",
  "Découvrez la méditation, la pleine conscience, les traditions spirituelles et la réflexion paisible.",
  "Mouvement et conscience du corps",
  "Explorez le yoga, le mouvement conscient et les traditions sri-lankaises comme l’Angampora.",
  "Énergie et traditions holistiques",
  "Découvrez le Reiki, la méditation des chakras et la relaxation sonore dans le respect des croyances.",
  "Nature et éco-bien-être",
  "Retrouvez les forêts, montagnes, plantations de thé et côtes du Sri Lanka à un rythme paisible.",
  "Alimentation et vie conscientes",
  "Découvrez les produits locaux, la cuisine sri-lankaise et des habitudes attentives.",
  "Créativité et expression personnelle",
  "Explorez l’écriture, la peinture, la musique et le mouvement comme espaces de réflexion.",
  "NOS VALEURS",
  "Les personnes avant les forfaits. Le sens avant le prix.",
  "Nous voulons créer un espace ouvert à l’apprentissage, au dialogue et aux expériences personnelles.",
  "Ouvert à tous",
  "Toutes les origines, croyances et expériences sont les bienvenues.",
  "Partager librement le savoir",
  "Nous partageons ce que nous savons et apprenons des autres.",
  "Une valeur juste",
  "Des expériences de qualité à des coûts raisonnables et transparents.",
  "Respect des personnes et des lieux",
  "Nous respectons les traditions, les communautés et la nature du Sri Lanka.",
  "LE SRI LANKA, À VOTRE FAÇON",
  "Pas un circuit standard. Votre expérience bien-être.",
  "Certains recherchent la méditation, d’autres la nature, la culture, le yoga ou le Reiki. Nous vous écoutons avant de construire un voyage réaliste.",
  "Avec Ask Ceylon, partagez vos préférences. Notre équipe préparera un projet et un devis. Aucune réservation n’est confirmée avant les accords et le paiement.",
  "Créer mon voyage — demande gratuite",
  "La valeur d’un voyage bien-être se mesure à ce que vous apprenez, ressentez et découvrez — pas à ce que vous dépensez.",
  "L’APPROCHE CEYLON WELLNESS",
  "NOTRE INVITATION",
  "Commencez par la curiosité. Trouvez votre chemin.",
  "Pour apprendre, partager ou découvrir le Sri Lanka autrement, vous êtes les bienvenus.",
  "Explorer le bien-être",
  "Découvrir un voyage personnel",
  "Nos contenus servent à l’éducation, à la détente et au bien-être général. Le Reiki et les autres pratiques énergétiques ne sont pas des traitements médicaux scientifiquement établis et ne remplacent pas les soins médicaux ou psychologiques."
 ],
 "ES": [
  "CEYLON WELLNESS · NUESTRA HISTORIA",
  "Bienestar a través del conocimiento, la conexión y la experiencia.",
  "Compartimos conocimientos, exploramos el bienestar y acercamos experiencias significativas de Sri Lanka a más personas.",
  "Conoce nuestro propósito",
  "Explora el bienestar",
  "POR QUÉ EXISTIMOS",
  "El bienestar no es un lujo. Es un camino que podemos compartir.",
  "Ceylon Wellness es una plataforma para compartir conocimientos y experiencias sobre bienestar físico, mental y espiritual.",
  "Compartimos lo aprendido, presentamos tradiciones y conectamos a personas interesadas en una vida más consciente.",
  "No estamos aquí solo para vender viajes. Viajar es una forma de experimentar el bienestar, no la razón de ser de esta comunidad.",
  "Creemos que las experiencias valiosas deben ser accesibles para distintos presupuestos, con calidad y precios justos.",
  "DOS FORMAS DE CONECTAR",
  "Aprende donde estés. Vive la experiencia cuando estés listo.",
  "01 · CONOCIMIENTO",
  "Aprender y compartir",
  "Descubre meditación, atención plena, yoga, Reiki, espiritualidad, naturaleza y vida consciente, sin imponer creencias.",
  "Explora nuestra guía",
  "02 · EXPERIENCIA",
  "Explorar y experimentar",
  "Te ayudamos a encontrar actividades y lugares en Sri Lanka según tus intereses, tiempo y presupuesto.",
  "Cuéntanos qué te importa",
  "DESCUBRE TU CAMINO",
  "Seis caminos hacia el bienestar.",
  "Distintas tradiciones ofrecen distintas formas de explorar el bienestar. Empieza por lo que te interese.",
  "Atención plena, espiritualidad y paz interior",
  "Explora meditación, atención plena, tradiciones espirituales y reflexión tranquila.",
  "Movimiento y conciencia corporal",
  "Conoce yoga, movimiento consciente y prácticas tradicionales de Sri Lanka, incluido Angampora.",
  "Energía y tradiciones holísticas",
  "Descubre Reiki, meditación de chakras y relajación con sonido, respetando distintas creencias.",
  "Naturaleza y bienestar ecológico",
  "Reconecta con bosques, montañas, plantaciones de té y costas de Sri Lanka a un ritmo tranquilo.",
  "Alimentación y vida conscientes",
  "Descubre ingredientes locales, cocina de Sri Lanka y hábitos conscientes.",
  "Creatividad y expresión personal",
  "Explora escritura, pintura, música y movimiento como formas de reflexión.",
  "LO QUE NOS IMPORTA",
  "Personas antes que paquetes. Propósito antes que precios.",
  "Queremos un espacio abierto al aprendizaje, al diálogo y a las experiencias personales.",
  "Abierto a todos",
  "Damos la bienvenida a personas de distintas culturas, creencias y experiencias.",
  "Conocimiento compartido",
  "Compartimos lo que sabemos y aprendemos de los demás.",
  "Valor justo",
  "Experiencias de calidad a precios razonables y transparentes.",
  "Respeto por las personas y el lugar",
  "Valoramos las tradiciones, comunidades y naturaleza de Sri Lanka.",
  "SRI LANKA, A TU MANERA",
  "No es un tour estándar. Es tu experiencia de bienestar.",
  "Algunos buscan meditación; otros, naturaleza, cultura, yoga o Reiki. Primero escuchamos y luego ayudamos a planear un viaje realista.",
  "En Ask Ceylon puedes compartir tus preferencias. Nuestro equipo preparará una propuesta y presupuesto. Ninguna reserva se confirma antes de los acuerdos y el pago.",
  "Diseña tu viaje — consulta gratuita",
  "El valor de un viaje de bienestar está en lo que aprendes, sientes y descubres, no en cuánto gastas.",
  "EL ENFOQUE CEYLON WELLNESS",
  "NUESTRA INVITACIÓN",
  "Empieza con curiosidad. Encuentra tu camino.",
  "Ya sea para aprender, compartir o descubrir Sri Lanka de otra manera, eres bienvenido.",
  "Explora el bienestar",
  "Explora un viaje personal",
  "Nuestros contenidos son educativos y de bienestar general. El Reiki y otras prácticas energéticas no son tratamientos médicos científicamente demostrados y no sustituyen la atención médica ni psicológica."
 ]
};
const english = ["CEYLON WELLNESS · OUR STORY", "Wellness through knowledge, connection & experience.", "Sharing what we have learned, exploring what wellbeing means to each of us, and making meaningful Sri Lankan wellness experiences more accessible.", "Discover our purpose", "Explore wellness", "WHY WE EXIST", "Wellness is not a luxury. It is a journey we can share.", "Ceylon Wellness is a knowledge-sharing and experience-led platform for people interested in physical, mental and spiritual wellbeing.", "We created this space to share our knowledge and lived experiences, introduce different wellness traditions, and connect with people who are curious about a more balanced, mindful way of life.", "We are not here simply to sell travel packages. Travel is one way to experience wellness in practice — not the reason this community exists.", "We believe meaningful wellbeing experiences should not be reserved for people with large budgets. Our aim is to offer honest guidance and help people find quality experiences at fair, accessible costs, with choices suited to their needs.", "TWO WAYS TO CONNECT", "Learn wherever you are. Experience when you are ready.", "01 · KNOWLEDGE", "Learn & Share", "Explore meditation, mindfulness, yoga, Reiki, spirituality, nature-based wellbeing and everyday mindful living. We share knowledge and experiences without asking you to adopt any particular belief.", "Explore our wellness guide", "02 · EXPERIENCE", "Explore & Experience", "If you wish to take your interest further, we can help you explore suitable wellness activities and places in Sri Lanka. Our human planning team considers your interests, available time and budget — not a fixed package.", "Tell us what matters to you", "DISCOVER YOUR OWN WAY", "Six pathways to wellbeing.", "Different traditions and practices offer different ways to explore wellness. Start with what interests you.", "Mindfulness, Spirituality & Inner Peace", "Explore meditation, mindfulness, spiritual traditions and quiet reflection. Discover perspectives that invite greater self-awareness and inner calm.", "Movement & Body Awareness", "Learn about yoga, mindful movement and Sri Lankan traditional practices, including Angampora, as ways to explore the relationship between body and mind.", "Energy & Holistic Traditions", "Discover Reiki, chakra-focused meditation, sound-based relaxation and other spiritual traditions with openness and respect for different beliefs.", "Nature & Eco-Wellness", "Reconnect with the forests, hills, tea country and coastlines of Sri Lanka through slower travel, nature immersion and peaceful reflection.", "Mindful Food & Living", "Explore fresh local ingredients, Sri Lankan culinary heritage, mindful eating and thoughtful everyday wellness habits.", "Creativity & Self-Expression", "Explore writing, painting, music, movement and other creative practices that make space for reflection and personal expression.", "WHAT MATTERS TO US", "People before packages. Purpose before price tags.", "We want this to be a welcoming space for learning, thoughtful conversation and experiences that feel personally meaningful.", "Open to everyone", "Different backgrounds, beliefs and levels of experience are welcome.", "Knowledge freely shared", "We share what we know and stay open to learning from others.", "Fair and thoughtful value", "We seek quality experiences at reasonable, transparent costs.", "Respect for people and place", "We value Sri Lankan traditions, local communities and nature.", "SRI LANKA, PERSONALLY EXPERIENCED", "Not a standard tour. Your own wellness experience.", "Some people come to learn meditation. Others want time in nature, cultural encounters, yoga, Reiki or quiet reflection. We listen first and help shape a realistic journey around your interests and budget.", "Through Ask Ceylon, you can share your preferences. Our Sri Lankan team can then prepare a personalised plan and quotation for you to review. No reservation is presented as confirmed before the necessary arrangements and payment.", "Design my journey — free to enquire", "We believe the value of a wellness journey is measured by what you learn, feel and discover — not how much you spend.", "THE CEYLON WELLNESS APPROACH", "OUR INVITATION", "Start with curiosity. Find your own path.", "Whether you are here to learn, to share, or to experience Sri Lanka in a meaningful way, you are welcome at Ceylon Wellness.", "Discover wellness", "Explore a personal journey", "Our content and experiences are for education, personal exploration, relaxation and general wellbeing. Reiki, chakra balancing and other energy-based traditions are not presented as scientifically established medical treatments. Nothing here replaces professional medical or mental-health care."];

const pathways = [
  { Icon: Flower2, title: 'Mindfulness, Spirituality & Inner Peace', text: 'Explore meditation, mindfulness, spiritual traditions and quiet reflection. Discover perspectives that invite greater self-awareness and inner calm.' },
  { Icon: Sun, title: 'Movement & Body Awareness', text: 'Learn about yoga, mindful movement and Sri Lankan traditional practices, including Angampora, as ways to explore the relationship between body and mind.' },
  { Icon: Sparkles, title: 'Energy & Holistic Traditions', text: 'Discover Reiki, chakra-focused meditation, sound-based relaxation and other spiritual traditions with openness and respect for different beliefs.' },
  { Icon: Waves, title: 'Nature & Eco-Wellness', text: 'Reconnect with the forests, hills, tea country and coastlines of Sri Lanka through slower travel, nature immersion and peaceful reflection.' },
  { Icon: Utensils, title: 'Mindful Food & Living', text: 'Explore fresh local ingredients, Sri Lankan culinary heritage, mindful eating and thoughtful everyday wellness habits.' },
  { Icon: Palette, title: 'Creativity & Self-Expression', text: 'Explore writing, painting, music, movement and other creative practices that make space for reflection and personal expression.' },
];

export default function AboutPage({ lang = 'EN' }: Props) {
  const t = (i:number) => translated[lang.toUpperCase()]?.[i] ?? english[i];
  return <main className="cwAbout">
    <section className="cwAboutHero" aria-labelledby="cwAboutTitle">
      <div className="cwAboutHeroGlow" aria-hidden="true" /><div className="cwAboutHeroPhoto" aria-hidden="true" />
      <div className="cwAboutWrap cwAboutHeroInner">
        <span className="cwAboutEyebrow">{t(0)}</span>
        <h1 id="cwAboutTitle">{t(1)}</h1>
        <p>{t(2)}</p>
        <div className="cwAboutHeroActions"><a href="#cwAboutPurpose" className="cwAboutBtn cwAboutBtnLight">{t(3)} <ArrowRight size={18}/></a><Link to="/wellness" className="cwAboutTextLink">{t(4)} <ArrowRight size={16}/></Link></div>
      </div>
    </section>

    <section id="cwAboutPurpose" className="cwAboutSection cwAboutWrap cwAboutIntro">
      <div><span className="cwAboutEyebrow cwAboutDarkEyebrow">{t(5)}</span><h2>{t(6)}</h2></div>
      <div className="cwAboutProse"><p>{t(7)}</p><p>{t(8)}</p><p>{t(9)}</p><p>{t(10)}</p></div>
    </section>

    <section className="cwAboutTint"><div className="cwAboutWrap cwAboutSection">
      <div className="cwAboutCentered"><span className="cwAboutEyebrow cwAboutDarkEyebrow">{t(11)}</span><h2>{t(12)}</h2></div>
      <div className="cwAboutDuo">
        <article className="cwAboutFeature"><div className="cwAboutFeatureIcon"><BookOpen size={28}/></div><span className="cwAboutKicker">{t(13)}</span><h3>{t(14)}</h3><p>{t(15)}</p><Link to="/wellness">{t(16)} <ArrowRight size={17}/></Link></article>
        <article className="cwAboutFeature"><div className="cwAboutFeatureIcon"><Compass size={28}/></div><span className="cwAboutKicker">{t(17)}</span><h3>{t(18)}</h3><p>{t(19)}</p><Link to="/ask-ceylon">{t(20)} <ArrowRight size={17}/></Link></article>
      </div>
    </div></section>

    <section className="cwAboutWrap cwAboutSection" id="cwAboutPathways"><div className="cwAboutCentered"><span className="cwAboutEyebrow cwAboutDarkEyebrow">{t(21)}</span><h2>{t(22)}</h2><p>{t(23)}</p></div><div className="cwAboutGrid">{pathways.map(({Icon,title,text},i)=><article className="cwAboutPath" key={title}><div className="cwAboutPathTop"><span>0{i+1}</span><Icon size={25} strokeWidth={1.6}/></div><h3>{t(24+i*2)}</h3><p>{t(25+i*2)}</p></article>)}</div></section>

    <section className="cwAboutValues"><div className="cwAboutWrap cwAboutSection cwAboutValuesInner"><div><span className="cwAboutEyebrow">{t(36)}</span><h2>{t(37)}</h2><p>{t(38)}</p></div><div className="cwAboutValueList"><div><Heart size={23}/><span><strong>{t(39)}</strong><small>{t(40)}</small></span></div><div><BookOpen size={23}/><span><strong>{t(41)}</strong><small>{t(42)}</small></span></div><div><HandHeart size={23}/><span><strong>{t(43)}</strong><small>{t(44)}</small></span></div><div><Leaf size={23}/><span><strong>{t(45)}</strong><small>{t(46)}</small></span></div></div></div></section>

    <section className="cwAboutWrap cwAboutSection cwAboutJourney"><div><span className="cwAboutEyebrow cwAboutDarkEyebrow">{t(47)}</span><h2>{t(48)}</h2><p>{t(49)}</p><p>{t(50)}</p><Link to="/ask-ceylon" className="cwAboutBtn cwAboutBtnGreen">{t(51)} <ArrowRight size={18}/></Link></div><div className="cwAboutJourneySide"><div className="cwAboutJourneyPhoto" role="img" aria-label="Sri Lankan tropical nature"/><div className="cwAboutJourneyQuote"><span>“</span><blockquote>{t(52)}</blockquote><small>{t(53)}</small></div></div></section>

    <section className="cwAboutClosing"><div className="cwAboutWrap"><span className="cwAboutEyebrow">{t(54)}</span><h2>{t(55)}</h2><p>{t(56)}</p><div className="cwAboutHeroActions"><Link to="/wellness" className="cwAboutBtn cwAboutBtnLight">{t(57)} <ArrowRight size={18}/></Link><Link to="/ask-ceylon" className="cwAboutTextLink">{t(58)} <ArrowRight size={16}/></Link></div></div></section>
    <div className="cwAboutDisclaimer cwAboutWrap">{t(59)}</div>
  </main>;
}
