import {useState} from 'react';
import './ReikiChakraMeditation.css';
import './ReikiPremium.css';

type Language='EN'|'PL'|'RU'|'DE'|'FR'|'ES';
const translations={
EN:['Reiki for a Balanced and Harmonious Life','Learn, practise and experience Reiki with Dr. Vipula Wanigasekera and Tatsiana.','Explore the courses','Book your experience','What is Reiki?','Our Reiki Courses','Meet your guides','Watch & discover','7 Chakras — a traditional framework','Self-Reiki & Meditation','Book Your Reiki Experience','Send via WhatsApp','Send via Email','A booking request is not confirmed until our team replies.','Level 1 — Foundations','Level 2 — Deepening Practice','Level 3 — Master Path','Levels 1 & 2 — Combined Programme','Level 3 — By Invitation','Certified Usui Reiki Level 1 & 2 practitioner','View full certificate','Reiki is a Japanese complementary spiritual and wellbeing practice associated with Mikao Usui. Some people use it for relaxation and reflection. It is not a medical treatment.','Training details, dates, fees and any certification are confirmed personally before registration.','Your message will open in your chosen app. Please press Send there to submit your request.'],
PL:['Reiki dla równowagi i harmonii','Poznaj i praktykuj Reiki z dr. Vipulą Wanigasekerą i Tatsianą.','Poznaj kursy','Zarezerwuj spotkanie','Czym jest Reiki?','Nasze kursy Reiki','Poznaj prowadzących','Filmy i inspiracje','7 czakr — tradycyjny model','Reiki dla siebie i medytacja','Zarezerwuj Reiki','Wyślij przez WhatsApp','Wyślij e-mailem','Rezerwacja wymaga potwierdzenia przez nasz zespół.','Poziom 1 — Podstawy','Poziom 2 — Pogłębienie praktyki','Poziom 3 — Ścieżka mistrzowska','Poziomy 1 i 2 — Wspólny program','Poziom 3 — Na zaproszenie','Praktykująca Reiki Usui z certyfikatami poziomów 1 i 2','Zobacz certyfikat','Reiki to japońska praktyka duchowa i wspierająca dobrostan, związana z Mikao Usui. Nie jest leczeniem medycznym.','Program, terminy, ceny i certyfikacja są potwierdzane przed zapisem.','Otworzymy wybraną aplikację. Naciśnij Wyślij, aby przesłać zgłoszenie.'],
RU:['Рейки для баланса и гармонии','Изучайте и практикуйте Рейки с доктором Випулой Ванигасекерой и Татьяной.','Посмотреть курсы','Записаться','Что такое Рейки?','Наши курсы Рейки','Наши наставники','Видео и практика','7 чакр — традиционная модель','Самопрактика Рейки и медитация','Записаться на Рейки','Отправить в WhatsApp','Отправить по Email','Запись подтверждается только после ответа команды.','Уровень 1 — Основы','Уровень 2 — Углублённая практика','Уровень 3 — Путь мастера','Уровни 1 и 2 — Общая программа','Уровень 3 — По приглашению','Практик Усуи Рейки с сертификатами 1 и 2 уровней','Открыть сертификат','Рейки — японская духовная практика, связанная с Микао Усуи. Она не заменяет медицинское лечение.','Программа, даты, стоимость и сертификация подтверждаются перед записью.','Откроется выбранное приложение. Нажмите «Отправить», чтобы передать запрос.'],
DE:['Reiki für Balance und Harmonie','Reiki mit Dr. Vipula Wanigasekera und Tatsiana lernen und erleben.','Kurse entdecken','Termin anfragen','Was ist Reiki?','Unsere Reiki-Kurse','Unsere Begleitung','Videos entdecken','7 Chakren — traditionelles Modell','Selbst-Reiki & Meditation','Reiki-Anfrage senden','Per WhatsApp senden','Per E-Mail senden','Eine Buchung ist erst nach persönlicher Bestätigung verbindlich.','Level 1 — Grundlagen','Level 2 — Vertiefung','Level 3 — Meisterweg','Level 1 & 2 — Kombiniertes Programm','Level 3 — Auf Einladung','Usui-Reiki-Praktizierende mit Zertifikaten für Level 1 und 2','Zertifikat ansehen','Reiki ist eine japanische spirituelle Wohlbefindenspraxis nach Mikao Usui und keine medizinische Behandlung.','Inhalte, Termine, Preise und Zertifizierung werden vor Anmeldung bestätigt.','Die gewählte App öffnet sich. Bitte dort auf Senden klicken.'],
FR:['Reiki pour l’équilibre et l’harmonie','Découvrez le Reiki avec Dr Vipula Wanigasekera et Tatsiana.','Découvrir les cours','Réserver','Qu’est-ce que le Reiki ?','Nos cours de Reiki','Vos accompagnants','Découvrir les vidéos','7 chakras — cadre traditionnel','Auto-Reiki et méditation','Réserver une expérience Reiki','Envoyer par WhatsApp','Envoyer par e-mail','La réservation reste à confirmer par notre équipe.','Niveau 1 — Fondements','Niveau 2 — Approfondissement','Niveau 3 — Parcours de maître','Niveaux 1 et 2 — Programme combiné','Niveau 3 — Sur invitation','Praticienne Usui Reiki certifiée niveaux 1 et 2','Voir le certificat','Le Reiki est une pratique japonaise de bien-être et de spiritualité liée à Mikao Usui, et non un traitement médical.','Programme, dates, tarifs et certification sont confirmés avant inscription.','Votre application s’ouvrira. Appuyez sur Envoyer pour transmettre la demande.'],
ES:['Reiki para el equilibrio y la armonía','Aprende y practica Reiki con el Dr. Vipula Wanigasekera y Tatsiana.','Explorar cursos','Reservar','¿Qué es Reiki?','Nuestros cursos de Reiki','Conoce al equipo','Ver vídeos','7 chakras — marco tradicional','Auto-Reiki y meditación','Reserva tu experiencia Reiki','Enviar por WhatsApp','Enviar por correo','La reserva requiere confirmación de nuestro equipo.','Nivel 1 — Fundamentos','Nivel 2 — Profundización','Nivel 3 — Camino de maestría','Niveles 1 y 2 — Programa combinado','Nivel 3 — Por invitación','Practicante certificada de Usui Reiki niveles 1 y 2','Ver certificado','Reiki es una práctica japonesa de bienestar y espiritualidad asociada a Mikao Usui; no es tratamiento médico.','Programa, fechas, precios y certificación se confirman antes de inscribirse.','Se abrirá la aplicación elegida. Pulsa Enviar para mandar la solicitud.']
} as const;
const coursePoints=[
['History of Reiki and Mikao Usui','Five Reiki principles and ethics','Self-Reiki hand positions','Meditation, mindfulness and daily practice','Traditional initiation / attunement: confirm with teacher'],
['Traditional Reiki symbols and their use','Intention and focused practice','Partner practice and boundaries','Distance Reiki as a traditional concept','Developing a responsible personal practice'],
['Advanced Reiki philosophy and meditation','Master-level practices and symbols','Teaching pathway and responsibilities','Individual guidance or invited group','Prerequisites and availability confirmed personally']
];
const chakras=[['Root','Muladhara','Grounding'],['Sacral','Svadhisthana','Creativity'],['Solar Plexus','Manipura','Confidence'],['Heart','Anahata','Compassion'],['Throat','Vishuddha','Expression'],['Third Eye','Ajna','Reflection'],['Crown','Sahasrara','Awareness']];
const lotusColors=['#C93D4C','#F47A3B','#E9B83E','#4A9D73','#4698C5','#6768B6','#A66BC5'];
function ChakraLotus({index}:{index:number}){
 const color=lotusColors[index];
 return <svg className="rcLotus" viewBox="0 0 100 100" role="img" aria-label={`${chakras[index][0]} lotus symbol`} xmlns="http://www.w3.org/2000/svg">
  <defs><radialGradient id={`rcGlow${index}`}><stop offset="0" stopColor="#fff" stopOpacity=".95"/><stop offset="1" stopColor={color} stopOpacity=".20"/></radialGradient></defs>
  <circle cx="50" cy="50" r="45" fill={`url(#rcGlow${index})`}/>
  {Array.from({length:[4,6,10,12,16,2,16][index]},(_,i)=>{const n=[4,6,10,12,16,2,16][index];return <ellipse key={i} cx="50" cy="27" rx="11" ry="22" transform={`rotate(${i*360/n} 50 50)`} fill={color} fillOpacity=".24" stroke={color} strokeWidth="1.4"/>;})}
  <circle cx="50" cy="50" r="17" fill="#fff" fillOpacity=".88" stroke={color} strokeWidth="1.6"/>
  <path d="M50 37 L63 50 L50 63 L37 50 Z" fill="none" stroke={color} strokeWidth="1.7"/>
  <circle cx="50" cy="50" r="4" fill={color}/>
 </svg>;
}
const meditationSteps=[
 {title:'Arrive & settle',duration:'1 minute',text:'Sit comfortably. Rest your hands gently. Notice where your body meets the chair or floor. You can keep your eyes open or softly closed.'},
 {title:'Gentle breathing',duration:'1 minute',text:'Breathe at your natural pace. Feel the air enter and leave. There is no need to hold your breath or change its rhythm.'},
 {title:'Self-Reiki & awareness',duration:'2 minutes',text:'If comfortable, place your hands lightly over your heart or on your lap. Notice warmth and contact without expecting any particular sensation.'},
 {title:'Return & reflect',duration:'1 minute',text:'Feel your feet, listen to the room and gently look around. Consider one intention for a calm, compassionate day.'}
];
function SelfMeditation(){
 const [step,setStep]=useState(0);
 return <div className="rcMeditation" aria-label="Five minute self meditation guide">
  <div className="rcMeditationTop"><span className="rcMeditationTag">✦ GUIDED SELF-PRACTICE</span><span className="rcMeditationTime">5 MIN · 4 STEPS</span></div>
  <h3>Five minutes of calm</h3><p className="rcMeditationIntro">A gentle, self-paced meditation you can follow without audio. Move through each step at your own rhythm.</p>
  <div className="rcMeditationProgress" aria-label={`Step ${step+1} of 4`}>{meditationSteps.map((_,i)=><span key={i} className={i<=step?'rcDone':''}/>)}</div>
  <div className="rcMeditationStep"><span>STEP {String(step+1).padStart(2,'0')} · {meditationSteps[step].duration}</span><h4>{meditationSteps[step].title}</h4><p>{meditationSteps[step].text}</p></div>
  <div className="rcMeditationControls"><button type="button" onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0}>← Previous</button><button type="button" onClick={()=>setStep(step===3?0:step+1)}>{step===3?'↻ Start again':'Next step →'}</button></div>
  <small>Pause or stop whenever you wish. This practice is for relaxation, not medical treatment.</small>
 </div>;
}
const videos=[['Reiki video','q6AIK2vQJ4c'],['Reiki short 01','JFK4XxlMzn4'],['Reiki short 02','UiQE_ado0T0'],['Reiki short 03','rVOkzXfZeLI']];
export default function ReikiPremium({lang}:{lang:Language}){
 const t=translations[lang]||translations.EN;
 const [programme,setProgramme]=useState('Levels 1 & 2 — Combined Programme');
 const [format,setFormat]=useState('Online');
 const [date,setDate]=useState('');
 const [name,setName]=useState('');
 const [email,setEmail]=useState('');
 const [phone,setPhone]=useState('');
 const [language,setLanguage]=useState<string>(lang);
 const [message,setMessage]=useState('');
 const [consent,setConsent]=useState(false);
 const [error,setError]=useState('');
 const bookingText=()=>`CEYLON WELLNESS — REIKI BOOKING REQUEST\nProgramme: ${programme}\nFormat: ${format}\nPreferred date: ${date||'Flexible'}\nPreferred language: ${language}\nFull name: ${name.trim()}\nEmail: ${email.trim()}\nWhatsApp: ${phone.trim()||'Not supplied'}\nMessage: ${message.trim()||'None'}\n\nPlease confirm availability, programme details and fees.`;
 const submit=(channel:'wa'|'email')=>{
  if(!name.trim()||!email.trim()||!email.includes('@')||!consent){setError('Please enter your name, valid email and accept the contact consent.');document.getElementById('reiki-book')?.scrollIntoView({behavior:'smooth'});return;}
  setError('');
  const txt=bookingText();
  const url=channel==='wa'?`https://wa.me/48696741450?text=${encodeURIComponent(txt)}`:`mailto:donwanigasekera@gmail.com?subject=${encodeURIComponent('Ceylon Wellness — Reiki Booking Request')}&body=${encodeURIComponent(txt)}`;
  if(channel==='wa')window.open(url,'_blank','noopener,noreferrer');else window.location.href=url;
 };
 const choose=(value:string)=>{setProgramme(value);document.getElementById('reiki-book')?.scrollIntoView({behavior:'smooth'});};
 return <main className="rp">
  <section className="rpHero" style={{backgroundImage:"linear-gradient(90deg,rgba(7,37,23,.87),rgba(7,37,23,.35) 65%,rgba(7,37,23,.10)),url('/images/reiki/reiki-hero.jpg')"}}>
   <div className="rpHeroInner"><span className="rpOverline">CEYLON WELLNESS · USUI REIKI</span><h1>{t[0]}</h1><p>{t[1]}</p><div className="rpHeroFeatures"><span>✧ Reiki Levels 1 & 2</span><span>❀ Self-Reiki & Meditation</span><span>◎ Online & Sri Lanka</span></div><div className="rpActions"><a href="#reiki-courses" className="rpBtn">{t[2]}</a><a href="#reiki-book" className="rpBtn rpBtnOutline">{t[3]}</a></div></div>
  </section>
  <div className="rpContainer">
   <section className="rpIntro" id="reiki-about"><div><span className="rpEyebrow">01 · THE PRACTICE</span><h2>{t[4]}</h2><p>{t[21]}</p><div className="rpBenefits"><span>✧ Relaxation</span><span>♡ Reflection</span><span>❀ Mindfulness</span><span>◌ Inner balance</span></div><blockquote>“A quiet moment to reconnect with yourself.”</blockquote></div><img src="/images/reiki/reiki-introduction.jpg" alt="Quiet meditation and Reiki self-practice"/></section>
   <section id="reiki-courses" className="rpSection"><span className="rpEyebrow">02 · TRAINING</span><h2>{t[5]}</h2><p>{t[22]}</p><div className="rpCourses">{coursePoints.map((items,i)=><article className="rpCourse" key={i}><img src={['/images/reiki/reiki-level-1.jpg','/images/reiki/reiki-level-2.jpg','/images/reiki/reiki-level-3.jpg'][i]} alt="Reiki course environment"/><div className="rpCourseBody"><span className="rpEyebrow">LEVEL 0{i+1}</span><h3>{t[14+i]}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul><button onClick={()=>choose(i===2?'Level 3 — Master Path':i===0?'Level 1 — Foundations':'Level 2 — Deepening Practice')}>{t[3]} →</button></div></article>)}</div><div className="rpCourseRibbon"><b>{t[17]}</b><span>Foundation + deepening practice in one learning pathway</span><button onClick={()=>choose('Levels 1 & 2 — Combined Programme')}>{t[3]} →</button></div></section>
   <section className="rpSection rpChakras"><span className="rpEyebrow">03 · AWARENESS</span><h2>{t[8]}</h2><p>The seven-chakra system is a traditional spiritual model, not scientifically established anatomy.</p><div className="rpChakraGrid rcChakraGrid">{chakras.map(([a,sanskrit,b],i)=><div key={a}><ChakraLotus index={i}/><b>{a}</b><small>{sanskrit}</small><small>{b}</small></div>)}</div></section>
   <section className="rpPractice"><img src="/images/reiki/reiki-meditation.jpg" alt="Traditional chakra colours in a peaceful nature setting"/><div><span className="rpEyebrow">04 · EVERYDAY PRACTICE</span><h2>{t[9]}</h2><p>Build a gentle personal routine that includes meditation, mindful breathing, traditional hand positions and reflective self-practice.</p><ul><li>Guided meditation and quiet reflection</li><li>Self-Reiki hand-position practice</li><li>Mindful breathing and body awareness</li><li>Respectful, non-medical wellbeing support</li></ul><SelfMeditation/></div></section>
   <section className="rpSection" id="reiki-team"><span className="rpEyebrow">05 · YOUR GUIDES</span><h2>{t[6]}</h2><div className="rpTeam"><article><img src="/images/reiki/reiki-practice.jpg" alt="Illustrative Reiki practice photograph; not a portrait of Dr. Vipula"/><div><h3>Dr. Vipula Wanigasekera</h3><b>Reiki Master Teacher · Wellness Guide</b><p>Reiki teacher named on Tatsiana’s Usui Reiki Level 1 and 2 certificates. Course arrangements and teaching availability are confirmed personally.</p><a href="/dr-vipula.html">View Dr. Vipula’s profile →</a></div></article><article><img src="/images/reiki/reiki-practice.jpg" alt="Illustrative Reiki practice photograph; not a portrait of Tatsiana"/><div><h3>Tatsiana Dzemesh</h3><b>{t[19]}</b><p>International presenter supporting English, Polish and Russian-speaking participants. Her original certificates are displayed below.</p><span className="rpLanguages">English · Polski · Русский</span></div></article></div><div className="rpCerts"><div className="rpCertHeading"><h3>Tatsiana’s Reiki certificates</h3><p>Original course-completion documents · Dr. Vipula Wanigasekera and Harshanie Hewamadduma</p></div><a href="/certificates/reiki-level-one.png" target="_blank" rel="noreferrer"><img src="/certificates/reiki-level-one.png" alt="Tatsiana Dzemesh Level 1 certificate dated 18 January 2026"/><b>Usui Reiki Level 1</b><small>18 January 2026 · {t[20]} ↗</small></a><a href="/certificates/reiki-level-two.png" target="_blank" rel="noreferrer"><img src="/certificates/reiki-level-two.png" alt="Tatsiana Dzemesh Level 2 certificate dated 22 February 2026"/><b>Usui Reiki Level 2</b><small>22 February 2026 · {t[20]} ↗</small></a></div></section>
   <section className="rpSection rpVideo"><span className="rpEyebrow">06 · VIDEO GALLERY</span><h2>{t[7]}</h2><p>Explore the supplied video links. Video subjects and appearances have not been independently verified.</p><div className="rpVideoGrid">{videos.map(([title,id],i)=><div key={id}><div className="rpVideoFrame"><iframe title={title} src={`https://www.youtube-nocookie.com/embed/${id}`} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><b>{i===0?'Featured Reiki video':`Reiki video · ${String(i).padStart(2,'0')}`}</b><a href={`https://www.youtube.com/watch?v=${id}`} target="_blank" rel="noreferrer">Watch on YouTube ↗</a></div>)}</div></section>
   <section id="reiki-book" className="rpBooking"><div className="rpBookingIntro"><span className="rpEyebrow">07 · PERSONAL ENQUIRY</span><h2>{t[10]}</h2><p>Select your programme and preferred format. Send the same details through WhatsApp or email. We reply personally to confirm the next steps.</p><img src="/images/reiki/reiki-booking.jpg" alt="Calm Reiki learning environment"/></div><div className="rpForm"><div className="rpFields"><label>Reiki programme<select value={programme} onChange={e=>setProgramme(e.target.value)}><option>Levels 1 & 2 — Combined Programme</option><option>Level 1 — Foundations</option><option>Level 2 — Deepening Practice</option><option>Level 3 — Master Path</option><option>Personal Reiki session</option></select></label><label>Training format<select value={format} onChange={e=>setFormat(e.target.value)}><option>Online</option><option>In Sri Lanka</option><option>Group invitation</option><option>One-to-one</option></select></label><label>Preferred date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Preferred language<select value={language} onChange={e=>setLanguage(e.target.value)}>{['EN','PL','RU','DE','FR','ES'].map(x=><option key={x} value={x}>{({EN:'English',PL:'Polski',RU:'Русский',DE:'Deutsch',FR:'Français',ES:'Español'} as Record<string,string>)[x]}</option>)}</select></label><label>Full name *<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label><label>Email address *<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>WhatsApp number<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+48 ..."/></label><label className="rpMessage">Additional message<textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Questions or preferred time..."/></label></div><label className="rpConsent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to share these details with Ceylon Wellness / Dr. Vipula for responding to my Reiki enquiry.</span></label>{error&&<p className="rpError" role="alert">{error}</p>}<div className="rpSend"><button className="rpWhatsApp" type="button" onClick={()=>submit('wa')}>◉ {t[11]}</button><button className="rpEmail" type="button" onClick={()=>submit('email')}>✉ {t[12]}</button></div><small>{t[23]}</small><p className="rcLegalNotice">Your message opens in WhatsApp or your email app; please press Send there. Your booking is not confirmed until we reply. Please do not include medical information. Read our <a href="/privacy-policy.html">Privacy Policy</a> and <a href="/booking-terms.html">Booking Terms</a>.</p><p className="rpPending">{t[13]}</p></div></section>
   <p className="rpNotice"><b>Wellness information:</b> Reiki is a complementary wellbeing/spiritual practice. There is no reliable scientific evidence that it treats health conditions or that its proposed energy field exists. It does not replace professional medical care.</p>
   <footer className="rcLegalFooter" aria-label="Legal information"><span>© Ceylon Wellness · Dr. Vipula Wanigasekera</span><nav aria-label="Legal links"><a href="/privacy-policy.html">Privacy Policy</a><a href="/medical-disclaimer.html">Medical Disclaimer</a><a href="/booking-terms.html">Booking Terms</a></nav></footer>
  </div>
 </main>;
}
